# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:s26QxlOhifAhV+NvKS2WtDJEpJ+HfQ68t4duyf6Zl64Z1ccXqw==,iv:v+ziEncEndePL9kHThrnPhUOpXy5Ze/vAAIL0lfjwlk=,tag:S2GST+c3wweNIcbhxOgCBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wxwc3qnqwcjhkxdkqh0junrysxp6y52uax2nnhtqmy8wg38uhfhqu60x3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNzZPNittSXlFNUExRkNu
            ZC9nNS9RbXdMODhRNzhJYzdka1c0YjYya1JBCnpzQWF6YWg0Z3dPQTN0aHg0dE5U
            WSt2UDd2RHpYSDMzcFBUYkoxVXUzaUUKLS0tIHJTaXcxeEJGWTZ2Qjd6bUYzZERx
            Nm5PVE5EOUU1WHMySE5kN1h6bzYrZW8KD2rw3hUxR/jNWh6KV96MBGtFuwtpeHAI
            /Cey6Lm5gC9N69ho4akn8QyhZ4yxshG0rTsomDte0MfCdfXUv4725g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-09T00:00:51Z"
    mac: ENC[AES256_GCM,data:Hu4S6te7IgspyEO1rZWLYgoSo+UAqd4DLliz02FFWBL1XMb+dRvBhcKxEEfSMP/RNfOcDoxzmQUyqQh/UgP80jja0MdEMpfNjnNnHKcDyvX2z0q2Car77oxP8rUJD1obkAMbDGOgNDTLal0qkCSaU6wlvM1t5cZ4Q6jo7xf3P4U=,iv:L83U+cRPjRG5n1hATJjIgN/Sv5brHOeHOol57Yurnxo=,tag:PzsfRkm/mv7nGHc8YZJacQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
