---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Etc/UTC
  METALLB_LB_RANGE: 10.0.4.40-10.0.4.50
  METALLB_K8S_GATEWAY_ADDR: 10.0.4.40
  METALLB_INGRESS_ADDR: 10.0.4.41
