# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:BeQZdGGwKxkuyQ==,iv:zqfWvOI2kGQZExL7G6Zukz5uNyti37pz9hiSEPrgJaE=,tag:AVIlJi7vRZYRQGz2fVH5IA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:vbA7aWTUZkK8hZXbkPVdqVU=,iv:hhELoTjcfYZuUzZ7tEkOWic8ZAUPgdiybA//993rHoY=,tag:jSOltNcWe/1tBtCE2v+OlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wxwc3qnqwcjhkxdkqh0junrysxp6y52uax2nnhtqmy8wg38uhfhqu60x3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1a0dNbVFzbU1IUkFzcUVX
            RlB0b0RQT2IxdVNKZ0RxajBFdTJnZXpQL3dRCk9mRXNFQXRmWmZKY0JOc1RBRFJr
            cllUSFZmQmI3ZHBmbUlHd0ZvdHZCcWMKLS0tIHdHMGFIL2xJWTc2WnQyaHVzeUE4
            Z1BSL3pBUG8yQjJNNXBqOWs2MmFjR1kKLO/vm3wnW3QB5nhNNlxyTJ6J/wnrSy0s
            c2HKJyyQXhXg69ZUQCvJuWIXH3sQUAPW6Woa/X4wjeRKHIAwV9rkCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-09T01:02:21Z"
    mac: ENC[AES256_GCM,data:PIi8XmzbW4LUZCE7GnlpHqfxzGoOzRWD7MQ/vAb3tDsL89Nm4cnSqja3d9T8KO+vye9FvfpO4EyXX553onlRVfBdQoxMR0HY0VffGVGGX9rH5xXU92p/Ote/rRpa7J5jhnoWF6mVZ00X6TRQicAOdfxhoqvmLZPYcsES2JHDFA0=,iv:DLGx0ZE5SuYy0SevhTki6nF9sHGFoYjF2O2Nd8JeJk0=,tag:InRNzVX6DL66xzbT6bo9mw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
