kind: Secret
ansible_user: ENC[AES256_GCM,data:C4o=,iv:iDwuEwynywRms35SwdRIHaDNTf8wBYMDIwM5naOYxAA=,tag:xgsniy18Yy/h6iPlNWUdvg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:COzhvzTC1YDe,iv:B3TjUUXmdwENfcqJt/DrevfcRZGvmWaVZQvFcabvDaw=,tag:7Lz/ZAaxShXy+jJ7so48eA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wxwc3qnqwcjhkxdkqh0junrysxp6y52uax2nnhtqmy8wg38uhfhqu60x3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcEN2SzZwbkVFa2VrRXV5
            Vm9ON2diU0N0VVpOMEcwSVRHNlVVWVJjSW5FCjFhUk0xcEZjNFZLMFhQaXN6aE1L
            M2UwakdmYVluYkNrMmZHSHI2RFRNRTgKLS0tIE1KTm9pbmJjWUx0aE0zVVVROXU0
            SUNnc0dCeHpJV3FSWFYyRHN1dFdhZTQKv1fKvN+xdOqcpIuEDVlKN7f3rq1BeUzz
            emI+0aEG6/sxi3BByAhRbgaMbYEWUlrCPYRwld5GvCAKYICMnHTCpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-09T01:02:21Z"
    mac: ENC[AES256_GCM,data:5gtYaCx/QjjmgE7VWxXfYrvG5GUCnuopKMOgd9rANPxIF972tdod0984Iq5ITmOP9iLX7wMt/DAkFVHEp+eqQ7d8oF1qgu1IxcsMTfbIefrxwxSyhnk7TO0Ehl+GJfkFrt0WW0EXjNNJGMl9qtQwZz3nSSLjlsbYMRy6zK3619s=,iv:oyrxCeR+5ff2AWf+WZm1ebfV31frJO9tvHhRQr8Ozmk=,tag:uOkN8zH80WnUNXLX2j/M/A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
