kind: Secret
ansible_user: ENC[AES256_GCM,data:tXY=,iv:bD3NqFuDtlBrnWOQvOaFS2dDVbRfkWBfVlmQFwKcyW4=,tag:CB3pVOhYMZH5NoPDs17ZNw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:oELg+b0blke2,iv:KpCZN7lR9d/NllsvC/I6F341JBUpSrR2fNq2rZULKzE=,tag:b5Q6A1aMJ8r1Nnkl9RLUpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wxwc3qnqwcjhkxdkqh0junrysxp6y52uax2nnhtqmy8wg38uhfhqu60x3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMXBUaFN6L2xHWE9JK09U
            RFcvall6MjRUdEdrYkdpM2FyOE1JcytZckJzClZYaFV6K2hVWWVSUDQ2L1pWTGd5
            NytnSVcwbWVyNEhwMmVhdWRHckRoeDQKLS0tIE4yTndPby9iOFRBUjFsdGd1M3hD
            VFN4SEJicTlLZjByVVM0K3pZNG9NMXMKBfDtmHyrdZXdlaop1lN6rp19gpO1juNR
            iBRhq6u+diFREuwj5JjStzqDeiwYA6kfVsf1qNTUvrNwRM5dmuc2FA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-09T00:00:51Z"
    mac: ENC[AES256_GCM,data:vIqupiBOIb0MM7R0bF/Um1cdXq1IoVG7lfhTHISndZEd/nY2w38SBOK8VzltGrfotnBeAF6oT8AA8IeTjY6LZITxYoNzoK4rjYiiyqOMOrXzoG/6u5khQftI6qVXnkBdcDf7U2WAjRz05MxMuedWMkh5OOHEBOUi2sqr6Fv1fyA=,iv:felvtHy15lQIHbJd3Pc2L7DewkcbJ0YwHiVWy55QYAw=,tag:grFUni19ktJLAGSwRQh8CQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
